# Generated by Django 3.0.3 on 2020-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default='This place is gorgeous'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
